services:
  db:
    image: postgres:16
    container_name: dp_app
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env-non-dev
    ports:
      - 5432:5432

  redis:
    image: redis:7
    container_name: cache

  main:
    build:
      context: .
    container_name: main_app
    env_file:
      - .env-non-dev
    depends_on:
      - db
      - redis
    command: ["/Base_app_dir/docker/app.sh"]
    ports:
      - 9000:8000

  celery:
    build:
      context: .
    container_name: booking_celery
    depends_on:
      - redis
    command: ["/Base_app_dir/docker/celery.sh", "celery"]
    env_file:
      - .env-non-dev

  flower:
    build:
      context: .
    container_name: booking_flower
    depends_on:
      - redis
    command: ["/Base_app_dir/docker/celery.sh", "flower"]
    env_file:
      - .env-non-dev
    ports:
      - 5555:5555
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheusdata:/prometheus
    restart: unless-stopped
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafanadata:/var/lib/grafana
    restart: unless-stopped
    ports:
      - 3000:3000

volumes:
  postgresdata:
  grafanadata:
  prometheusdata:

